modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "G9third"
description = '''PMWeather XYZ wind for Sable/Create Aeronautics, plus generic caller-buffer body pressure and virtual lifting-surface APIs for external rigid-body owners.'''

[[mixins]]
config = "pmweather_aeronautics.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.234,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sable"
type = "required"
versionRange = "[2.0.5,3.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "pmweather"
type = "required"
versionRange = "[0.17.14,0.17.17)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aeronautics_bundled"
type = "optional"
versionRange = "[1.2.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aeronautics"
type = "optional"
versionRange = "[1.2.1,)"
ordering = "AFTER"
side = "BOTH"
